"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const ims_common_1 = require("ims-common");
exports._INITIAL_STATE = ims_common_1.InjectionToken.fromString("@ngrx/store Internal Initial State");
exports.INITIAL_STATE = ims_common_1.InjectionToken.fromString("@ngrx/store Initial State");
exports.REDUCER_FACTORY = ims_common_1.InjectionToken.fromString("@ngrx/store Reducer Factory");
exports._REDUCER_FACTORY = ims_common_1.InjectionToken.fromString("@ngrx/store Reducer Factory Provider");
exports.INITIAL_REDUCERS = ims_common_1.InjectionToken.fromString("@ngrx/store Initial Reducers");
exports._INITIAL_REDUCERS = ims_common_1.InjectionToken.fromString("@ngrx/store Internal Initial Reducers");
exports.META_REDUCERS = ims_common_1.InjectionToken.fromString("@ngrx/store Meta Reducers");
exports.STORE_FEATURES = ims_common_1.InjectionToken.fromString("@ngrx/store Store Features");
exports._STORE_REDUCERS = ims_common_1.InjectionToken.fromString("@ngrx/store Internal Store Reducers");
exports._FEATURE_REDUCERS = ims_common_1.InjectionToken.fromString("@ngrx/store Internal Feature Reducers");
exports._FEATURE_CONFIGS = ims_common_1.InjectionToken.fromString("@ngrx/store Internal Feature Configs");
exports._STORE_FEATURES = ims_common_1.InjectionToken.fromString("@ngrx/store Internal Store Features");
exports._FEATURE_REDUCERS_TOKEN = ims_common_1.InjectionToken.fromString("@ngrx/store Internal Feature Reducers Token");
exports.FEATURE_REDUCERS = ims_common_1.InjectionToken.fromString("@ngrx/store Feature Reducers");
