"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var sync_1 = require("./sync");
exports.syncHistoryWithStore = sync_1.default;
var reducer_1 = require("./reducer");
exports.LOCATION_CHANGE = reducer_1.LOCATION_CHANGE;
exports.routerReducer = reducer_1.routerReducer;
var actions_1 = require("./actions");
exports.CALL_HISTORY_METHOD = actions_1.CALL_HISTORY_METHOD;
exports.push = actions_1.push;
exports.replace = actions_1.replace;
exports.go = actions_1.go;
exports.goBack = actions_1.goBack;
exports.goForward = actions_1.goForward;
exports.routerActions = actions_1.routerActions;
var middleware_1 = require("./middleware");
exports.routerMiddleware = middleware_1.default;
